### PR TITLE
fix: hide tree on checks panel

### PR DESCRIPTION
**Pull request by corporateanon**
### Fixed
 * (#170) hide tree view in Checks tab

### CODE REVIEW

**Comment by berzniz** [comment]
Thank you. I will review. I'm wondering if there's a way to detect the appearance of files in a more generic way. Maybe other pages have file diffs that we are not aware of (or added later by GitHub)

**Comment by corporateanon** [comment]
Yes, but i think that it's more reliable to maintain a whitelist of pages we support, because even if Github will eventually add file diffs on other pages, we anyway need to test how the tree view looks on those pages. For example, GH does show file diffs under a PR creation form, and i think that tree view embedding needs to be designed separately for this case.

Also, I would like better to rely on page URLs instead of DOM elements, when deciding whether tree should be shown. We could even use some router lib for better readability. What do you think?

**Comment by dennisroche** [comment]
> Thank you. I will review. I'm wondering if there's a way to detect the appearance of files in a more generic way. Maybe other pages have file diffs that we are not aware of (or added later by GitHub)

I think this PR looks is good enough to merge. 

It is annoying to close the `tree` each time navigating to the `checks` tab.

**Comment by berzniz** [comment]
I am opting for a simpler more general fix: https://github.com/berzniz/github_pr_tree/pull/174

Thanks @corporateanon, your work made it easier to explore the options.

**Pull request closed without merging**
