### PR TITLE
Reload button to manually reload file tree

### PR DESCRIPTION
**Pull request by Linus045**
When looking at a single commit of a PR the file tree doesn't update correctly when the page is still loading.
This is because we stop trying to reload the file tree after the first time since we can't get the changed file count for the single commit.

I added a reload button that manually reloads the file tree when clicked.
Additionally I added a feature so that if you look at a single commit, it tries to refresh the tree a few times (max. 10 times currently).

Normally I don't program in React so there might be some things that can be done in a better fashion.

image

### CODE REVIEW

**Comment by Linus045** [comment]
This also acts as a workaround for #67

**Comment by berzniz** [comment]
Thanks @Linus045 ! I will go over it soon (crazy times so may take more time than usual) and it should be included in the next version.

**Comment by Linus045** [comment]
I suppose you can checkout this branch, build and add the extension to your browser and see how it performs on small and big pull requests.

The main goal is to fix the problem with github's batch loading when the PR contains a lot of changes.
Not all files are loaded instantaneously but rather it's split up in small batches.

Currently the tree is generated once and only updates when you type something in the filter bar.
This causes problems because not all files that changed are listed in the sidebar after the first batch load.
This PR adds the ability to manually reload the tree as well as automatically tries to reload the tree a few times when you filter for something (10 times max with 1 second delay in-between).

**Comment by Linus045** [comment]
I removed the automatic reloading and replaced the bind(this) function with an arrow function.

**Pull request merged**
