### PR TITLE
github link structure changed

### PR DESCRIPTION
**Pull request by norbertnogacki-tomtom**
this fixes issue https://github.com/berzniz/github_pr_tree/issues/206

### CODE REVIEW

**Comment by DarkHelmet67** [comment]
I think this is a quite safe fix
It will stop working only if GitHub changes (again) the anchor class/selector
Another solution could be to use
`.file-info > span.Truncate > a`
as the new selector

**Comment by kopach** [comment]
Seems like a duplicate of https://github.com/berzniz/github_pr_tree/pull/207

**Comment by DarkHelmet67** [comment]
> Seems like a duplicate of #207

IMHO the selector in this PR is safer, I'd close #207 and keep #208

**Comment by berzniz** [comment]
thanks @norbertnogacki-tomtom . Will test and deploy soon

**Pull request merged**
