### PR TITLE
Fixed firefox support, added popup menu

### LINKED ISSUE #93: Extension not working for Github enterprise in Firefox
When trying to use the extension with Github Enterprise in Firefox the first thing I encountered is that the icon was not showing up. After tinkering a little bit (never played with extensions before) I managed to make it show up by adding the following conf to the firefox manifest:

```
  "browser_action": {
    "default_icon": {
    "16": "16x16.png",
    "48": "48x48.png",
    "128": "128x128.png"
    }
```

The second one was when trying to enable the extension in my github enterprise domain, when clicking "Enable Better Pull Request for GitHub on this domain", I do not see the file tree and this appears in the inspector:

```
undefined is not a valid URL. background.js line 120 > eval:34
    addContextMenu webpack:///./node_modules/webext-domain-permission-toggle/webext-domain-permission-toggle.js?:34
    apply self-hosted:1875
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:600
    applySafe resource://gre/modules/ExtensionCommon.jsm:583
    sync resource://gre/modules/ExtensionCommon.jsm:2418
    listener chrome://browser/content/child/ext-menus.js:273
    withHandlingUserInput resource://gre/modules/ExtensionCommon.jsm:120
    listener chrome://browser/content/child/ext-menus.js:272
    apply self-hosted:1875
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.jsm:600
    fire resource://gre/modules/ExtensionChild.jsm:1237
    recvRunListener resource://gre/modules/ExtensionChild.jsm:1241
    recvRunListener self-hosted:878
    _recv resource://gre/modules/ConduitsChild.jsm:78
    receiveMessage resource://gre/modules/ConduitsChild.jsm:169
```

I managed to make it work by adding my domain under permissions and the content script "matches".

```
  "permissions": [
    "contextMenus",
    "storage",
    "*://*.github.com/*",
    "*://*github.mydomain.com/*"
  ],
```

```
  "content_scripts": [
    {
      "matches": [
        "*://*.github.com/*",
    "*://*.github.int.mydomain.com/*"
      ],
      "run_at": "document_idle",
      "js": [
        "better_github_prs.js"
      ],
      "css": []
    }
  ],
```

Sadly I couldn't come up with a general solution I could send as PR. Hope this helps :)

Thanks for your awesome work!

### PR DESCRIPTION
**Pull request by adambriny**
## In this PR
- Fixed #93.
- Added popup menu to the extension icon, added padding to the popup
- Fixed opening extension options in firefox from the PR tree
- Added Firefox store link when in Firefox

### Firefox left-click popup
firefox_popup

### Firefox right-click menu
firefox_rightclick

### Firefox extension settings
firefox_options

### Firefox options from PR tree
firefox-options-from-page

### Chrome left-click popup
chrome_popup

### CODE REVIEW

**Comment by berzniz** [comment]
Hi Adam,

Thanks for submitting this PR! This looks great.

I’ll have to test and merge it, and I’ll hopefully do it soon. Times are a bit crazy right now, so my availability is not as usual. I do hope to have time to test and merge it next week.

From the top of my head, I remember placing the options in a pop up caused the extension storage not to work. I’ll have to review again.

**Comment by adambriny** [comment]
Thanks you! 😊 Sure, I think the couple weeks were a bit crazy for many of us. 
Regarding the pop up, I didn't experienced any issue with it, but mostly I checked it on Firefox.
I can't wait to see it released.

**Comment by berzniz** [comment]
Code looks good, well done 👏 

Going through some testing now to make sure everything works on both browsers.

**Comment by berzniz** [comment]
Great. I tested and the new functionality works on Firefox and there are no regressions. The Chrome options popup doesn't work, but this can be handled in a different PR in the future.

**Comment by berzniz** [comment]
This will be included in version `1.0.128`, submitted today to Mozilla

**Comment by adambriny** [comment]
Cool, already got the update. 👍  I'll check the options popup issue in Chrome next week.

**Comment by adambriny** [comment]
@berzniz I took a look on the options popup on Chrome, and I worked like charm to me. I could modify the settings and the were applied after a tab refresh. The chrome version was `81.0.4044.92 (64 bit)` and I built and loaded the extension in dev mode.

**Pull request merged**
