### PR TITLE
Concatenate single folders together

### PR DESCRIPTION
**Pull request by jacr1**
Folders containing only a single folder are concatenated together, so that the tree becomes smaller. 
image

Functionally that is found in other peer review systems:
image

### CODE REVIEW

**Comment by berzniz** [comment]
On https://github.com/facebook/react/pull/13761/files it appears to not show the folder structure at all, which isn't favorable from current state:
image

**Comment by jacr1** [comment]
Hello Berxniz, 

Have fixed the issue you found, where it ignored the top level. Will write a unit test for it ASAP.

**Comment by berzniz** [comment]
Perfect - I will then test it a bit, merge it and deploy to the chrome store

**Comment by berzniz** [comment]
Oh - I never configured tests for the project... well, let's skip it for now. I'll add unit tests system (`jest`) later on. I'll merge it today/tomorrow

**Comment by berzniz** [comment]
Going to merge this, this will appear in the next version (1.0.11)

**Pull request merged**
