### PR TITLE
Update due to GitHub DOM changes

### LINKED ISSUE #95: Extension not working anymore (Chrome)
image

### PR DESCRIPTION
**Pull request by berzniz**
Closes #95

### CODE REVIEW

**Comment by mihaituhari** [comment]
Awesome, that was fast 🎩 
Waiting for the release so I can update the extension. Many thanks!

**Comment by berzniz** [comment]
Thanks - I use it every day at work so I wanted to fix it quickly.

It is now pending Google review and hopefully will be available in the Chrome Store soon

**Comment by mihaituhari** [comment]
awesome! great work mate, much love <3

**Comment by mihaituhari** [comment]
@berzniz Do you know how long it usually takes for Chrome Store to publish the updates?
I can still see `1.0.25` there 😞

**Comment by berzniz** [comment]
From past experience: between 5 minutes to two weeks. Unfortunately I have no way to expedite this.

You can always clone the repo and install the development version which already includes the fix. It’s less work than it sounds

**Pull request merged**
