### PR TITLE
fix: fileId when CODEOWNERS exists

### LINKED ISSUE #110: Extension doesn't work with CODE OWNERS feature
Hi there,
Looks like GitHub updated the markup again and your wonderful extensions isn't working

```
Uncaught TypeError: Cannot read property 'parentElement' of null
    at u (better_github_prs.js:1)
    at s (better_github_prs.js:1)
    at better_github_prs.js:1
    at Array.forEach (<anonymous>)
    at better_github_prs.js:1
    at Array.forEach (<anonymous>)
    at b (better_github_prs.js:1)
    at n.value (better_github_prs.js:31)
    at n.value (better_github_prs.js:31)
    at La (better_github_prs.js:22)
```

### PR DESCRIPTION
**Pull request by mychaelgo**
fix #110 

Screenshot

Screen Shot 2020-05-01 at 08 48 06

@berzniz  please help to review & test. working fine on my Chrome Mac 🙏

### CODE REVIEW

**Comment by RussKie** [comment]
Interestingly enough it is working in this repo:
image

...but not working in dotnet repos for me. Here's another repo:
e.g. https://github.com/dotnet/roslyn-analyzers/pull/3588/files
image

I ran the selectors - both old and the new - in this PR:
image

...and they both are working too. E.g. https://github.com/dotnet/winforms/pull/3064/files
image
image


So I think there may be something else that's not working.

**Comment by mychaelgo** [comment]
@RussKie 

it works for me on https://github.com/dotnet/roslyn-analyzers/pull/3588/files
Screenshot
Screen Shot 2020-05-01 at 09 08 35

**Comment by mychaelgo** [comment]
Screen Shot 2020-05-01 at 09 21 01

and there is different result between `.file-info > a.link-gray-dark` & `.file-info > a`
- `.file-info > a.link-gray-dark` get the correct fileid only
- `.file-info > a` get the correct fileid & `CODEOWNER` element

**Comment by RussKie** [comment]
Thank you 👍 
My JS and CSS are pretty basic

**Comment by berzniz** [comment]
Hi @mychaelgo -- I've suggested an alternative solution in #113 . The benefit is to make it future proof (as much as possible), so if other `a` links appear they will not break the extension.

Comments and feedback are welcomed

**Comment by berzniz** [comment]
Thanks for the PR and all the effort with testing and providing examples. We will use the fix from #113

**Pull request closed without merging**
