### PR TITLE
fix search selector in GitHub Enterprise

### PR DESCRIPTION
**Pull request by shatee**
fix https://github.com/berzniz/github_pr_tree/issues/100

Element ID changed to sequential number in GitHub Enterprise. (e.g. `diff-0`, `diff-1` ...)
I changed to refer to data-anchor attribute instead.

and update fixture.

### CODE REVIEW

**Comment by berzniz** [comment]
That's for the update. I do not use GitHub Enterprise myself so this is very helpful.

I'll test that this works on the regular GitHub as well and merge.

**Comment by sebarys** [comment]
Hi @berzniz 
Is any chance to merge this during this week?

**Comment by berzniz** [comment]
Yes. I will merge this today and upload to the store for review. Just want to make sure it doesn't break for non-enterprise GitHub users.

In the meantime, you can clone `shatee:fix-id` and run it locally. Should take less than 10 minutes in total to have it running on your browser

**Comment by painhardcore** [comment]
@berzniz can't make it to work :( cloned shatee's version
Used `yarn build` and then loaded to extensions

**Pull request merged**
